name: appname # Name must be unique for each app!
recipe: wordpress
excludes:
  - vendor
  - node_modules
  - modules/contrib
config:
  php: '7.4'
  via: nginx
  database: mariadb
  xdebug: true
  config:
    php: php.ini
services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  pma:
    type: phpmyadmin
    hosts:
      - database
  node:
    type: node
    build:
      - npm install
    globals:
      gulp-cli: latest
  appserver:
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=appserver"
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  yarn:
    service: node
  
  admin:reset:
    service: appserver
    cmd: wp user update 1 --user_email=test@test.com && wp user update 1 --user_pass=admin
  
  upload:db:
    service: appserver
    level: app
    cmd: /app/connect.sh --mode=puDB
    options:
      env:
        passthrough: true
        alias:
          - e
        describe: What environment are we using
        interactive:
          type: list
          choices:
            - DEV
            - STG
            - PRD
          message: What environment should we push the database to?
          default: DEV
          weight: 600

  download:db:
    service: appserver
    level: app
    cmd: /app/connect.sh --mode=plDB
    options:
      env:
        passthrough: true
        alias:
          - e
        describe: What environment are we using
        interactive:
          type: list
          choices:
            - DEV
            - STG
            - PRD
          message: What environment should we pull the database from?
          default: DEV
          weight: 600

  download:media:
    service: appserver
    level: app
    cmd:
      - /app/connect.sh --mode=plFS
    options:
      env:
        passthrough: true
        alias:
          - e
        describe: What environment are we using
        interactive:
          type: list
          choices:
            - DEV
            - STG
            - PRD
          message: What environment should we pull the uploads directory from?
          default: DEV
          weight: 600
          
  upload:media:
    service: appserver
    level: app
    cmd:
      - /app/connect.sh --mode=puFS
    options:
      env:
        passthrough: true
        alias:
          - e
        describe: What environment are we using
        interactive:
          type: list
          choices:
            - DEV
            - STG
            - PRD
          message: What environment should we push the media to?
          default: DEV
          weight: 600
  install:wordpress:
    service: appserver
    cmd:
      - wp core download && wp config create --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbhost=database
events:
  post-start:
    - if [ ! -f wp-config.php ]; then wp core download && wp config create --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbhost=database && wp core install --url=http://$LANDO_APP_NAME.$LANDO_DOMAIN --title=$LANDO_APP_NAME --admin_user=admin --admin_email=admin@admin.com ; fi
    - composer update
#If you want to have lando source environment variables, provide the .env files here. Useful for composer.    
env_file:
